baseURL = "https://tfujiwara.github.io/blog/"
title = "El blog de TFujiwara"
languageCode = "es"
DefaultContentLanguage = "es" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "El blog de TFujiwara"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Blog personal donde cuento algunas de las investigaciones que he hecho, además de algún que otro tutorial o recomendaciones varias." 

    # The description of your website. It will be displayed in the home page
    #mainpagedesc = "This theme is the Hugo port of the BOOTSTRA.386 theme for a cool retro look on your blog. Check the links below to access the posts."

    # The name to display in the copyright section in the footer
    copyrightname = "Cristian Garcia Quevedo"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    #copyrighturl = "http://jmf-portfolio.netlify.com"

    # Show the "built on Hugo" disclaimer
    showhugo = false

    # Urls for social networks
    #facebook = "https://facebook.com"
    twitter = "https://twitter.com/TFujiwara86"
    linkedin = "https://www.linkedin.com/in/cgarciaquevedo/"
    github = "https://github.com/TFujiwara"
    gitlab = "https://gitlab.com/TFujiwara"
    telegram = "https://t.me/SeguridadInformatica"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "Cristian Garcia Quevedo"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    #url = "http://jmf-portfolio.netlify.com"

    # Text to go before copyright information
    #prefix = "[hugo.386 theme by Max le Fou](https://gitlab.com/maxlefou/hugo.386)"

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = "El blog de TFujiwara"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "Sobre mí"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true